### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [23]:
import pandas as pd
import numpy as np

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

In [2]:
cars1 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv", sep=",")
cars2 = pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv", sep=",")

   ### Step 3. Assign each to a to a variable called cars1 and cars2

In [ ]:
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [6]:
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [10]:
cars1.dropna(axis=1, how="all", inplace=True)

In [11]:
cars1

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
193,24.0,6,200,81,3012,17.6,76,1,ford maverick
194,22.5,6,232,90,3085,17.6,76,1,amc hornet
195,29.0,4,85,52,2035,22.2,76,1,chevrolet chevette
196,24.5,4,98,60,2164,22.1,76,1,chevrolet woody
197,29.0,4,90,70,1937,14.2,76,2,vw rabbit

### Step 5. What is the number of observations in each dataset?

In [18]:
cars1.shape

(198, 9)

In [19]:
cars2.shape

(200, 9)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [22]:
cars = pd.merge(cars1, cars2, how="outer")
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,9.0,8,304,193,4732,18.5,70,1,hi 1200d
1,10.0,8,307,200,4376,15.0,70,1,chevy c20
2,10.0,8,360,215,4615,14.0,70,1,ford f250
3,11.0,8,318,210,4382,13.5,70,1,dodge d200
4,11.0,8,350,180,3664,11.0,73,1,oldsmobile omega
...,...,...,...,...,...,...,...,...,...
393,43.4,4,90,48,2335,23.7,80,2,vw dasher (diesel)
394,44.0,4,97,52,2130,24.6,82,2,vw pickup
395,44.3,4,90,48,2085,21.7,80,2,vw rabbit c (diesel)
396,44.6,4,91,67,1850,13.8,80,3,honda civic 1500 gl
397,46.6,4,86,65,2110,17.9,80,3,mazda glc

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [32]:
n = cars.shape[0]
cars["owner"] = np.random.randint(15000, 73000, n)
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owner
0,9.0,8,304,193,4732,18.5,70,1,hi 1200d,17845
1,10.0,8,307,200,4376,15.0,70,1,chevy c20,71705
2,10.0,8,360,215,4615,14.0,70,1,ford f250,19849
3,11.0,8,318,210,4382,13.5,70,1,dodge d200,30151
4,11.0,8,350,180,3664,11.0,73,1,oldsmobile omega,37600
...,...,...,...,...,...,...,...,...,...,...
393,43.4,4,90,48,2335,23.7,80,2,vw dasher (diesel),61168
394,44.0,4,97,52,2130,24.6,82,2,vw pickup,47082
395,44.3,4,90,48,2085,21.7,80,2,vw rabbit c (diesel),59551
396,44.6,4,91,67,1850,13.8,80,3,honda civic 1500 gl,57841
397,46.6,4,86,65,2110,17.9,80,3,mazda glc,51623

### Step 8. Add the column owners to cars

In [ ]:
# Ya esta unida en la celda anterior

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,ownsers,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN,53251,27606
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN,59422,49090
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN,37971,67750
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN,26677,51476
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN,36778,23633
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl,NaN,NaN,NaN,NaN,NaN,60497,63289
196,44.0,4,97,52,2130,24.6,82,2,vw pickup,NaN,NaN,NaN,NaN,NaN,21235,37321
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage,NaN,NaN,NaN,NaN,NaN,17390,51911
198,28.0,4,120,79,2625,18.6,82,1,ford ranger,NaN,NaN,NaN,NaN,NaN,59976,36185
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10,NaN,NaN,NaN,NaN,NaN,28733,71615