# Occupation

In [1]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user).

In [2]:
users = pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user", sep="|")

### Step 3. Assign it to a variable called users.

In [3]:
users

     user_id  age gender     occupation zip_code
0          1   24      M     technician    85711
1          2   53      F          other    94043
2          3   23      M         writer    32067
3          4   24      M     technician    43537
4          5   33      F          other    15213
..       ...  ...    ...            ...      ...
938      939   26      F        student    33319
939      940   32      M  administrator    02215
940      941   20      M        student    97229
941      942   48      F      librarian    78209
942      943   22      M        student    77841

[943 rows x 5 columns]

### Step 4. Discover what is the mean age per occupation

In [4]:
round(users.groupby("occupation")["age"].mean(), 2)

occupation
administrator    38.75
artist           31.39
doctor           43.57
educator         42.01
engineer         36.39
entertainment    29.22
executive        38.72
healthcare       41.56
homemaker        32.57
lawyer           36.75
librarian        40.00
marketing        37.62
none             26.56
other            34.52
programmer       33.12
retired          63.07
salesman         35.67
scientist        35.55
student          22.08
technician       33.15
writer           36.31
Name: age, dtype: float64

### Step 5. Discover the Male ratio per occupation and sort it from the most to the least

In [5]:
# Nos piden hombres / total personas por ocupacion

In [6]:
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [7]:
lista_n = []
for x in users["gender"]:
    if x == "M":
        lista_n.append(1)
    else:
        lista_n.append(0)

users["gender_n"] = lista_n
users

     user_id  age gender     occupation zip_code  gender_n
0          1   24      M     technician    85711         1
1          2   53      F          other    94043         0
2          3   23      M         writer    32067         1
3          4   24      M     technician    43537         1
4          5   33      F          other    15213         0
..       ...  ...    ...            ...      ...       ...
938      939   26      F        student    33319         0
939      940   32      M  administrator    02215         1
940      941   20      M        student    97229         1
941      942   48      F      librarian    78209         0
942      943   22      M        student    77841         1

[943 rows x 6 columns]

In [8]:
users.groupby("occupation")["gender_n"].mean().sort_values(ascending=False)

occupation
doctor           1.000000
engineer         0.970149
technician       0.962963
retired          0.928571
programmer       0.909091
executive        0.906250
scientist        0.903226
entertainment    0.888889
lawyer           0.833333
salesman         0.750000
educator         0.726316
student          0.693878
other            0.657143
marketing        0.615385
writer           0.577778
none             0.555556
administrator    0.544304
artist           0.535714
librarian        0.431373
healthcare       0.312500
homemaker        0.142857
Name: gender_n, dtype: float64

In [10]:
users.groupby("gender").mean(numeric_only=True)

           user_id        age  gender_n
gender
F       481.406593  33.813187       0.0
M       468.167164  34.149254       1.0

In [70]:
users["ratio"] = users.groupby("occupation")["gender_n"].transform("mean") * 100
users.sort_values(by="ratio", ascending=False)

     user_id  age gender occupation zip_code  gender_n       ratio
934      935   42      M     doctor    66221         1  100.000000
844      845   64      M     doctor    97405         1  100.000000
298      299   29      M     doctor    63108         1  100.000000
840      841   45      M     doctor    47401         1  100.000000
426      427   51      M     doctor    85258         1  100.000000
..       ...  ...    ...        ...      ...       ...         ...
707      708   26      F  homemaker    96349         0   14.285714
361      362   35      F  homemaker    85233         0   14.285714
355      356   32      F  homemaker    92688         0   14.285714
897      898   23      M  homemaker    61755         1   14.285714
34        35   20      F  homemaker    42459         0   14.285714

[943 rows x 7 columns]

In [118]:
users.groupby("occupation")["gender"].count()

occupation
administrator     79
artist            28
doctor             7
educator          95
engineer          67
entertainment     18
executive         32
healthcare        16
homemaker          7
lawyer            12
librarian         51
marketing         26
none               9
other            105
programmer        66
retired           14
salesman          12
scientist         31
student          196
technician        27
writer            45
Name: gender, dtype: int64

In [ ]:
# users["ratio"] = users[users["gender"] == "M"].groupby("occupation")["gender"].count() / users.groupby("occupation")["gender"].count()
# users["ratio"] = users[users["gender"] == "F"].groupby("occupation")["gender"].count() / users.groupby("occupation")["gender"].count()

In [ ]:
# hombres = users[users["gender"] == "M"].groupby("occupation")["gender"].count()
# mujeres = users[users["gender"] == "F"].groupby("occupation")["gender"].count()
# total = users.groupby("occupation")["gender"].count()

# ratios = {"M": users["occupation"].map(hombres / total),
#           "F": users["occupation"].map(mujeres / total)}

# users["ratio"] = users["gender"].map(ratios)

In [121]:
users.groupby("occupation")["gender"].value_counts()

occupation     gender
administrator  M          43
               F          36
artist         M          15
               F          13
doctor         M           7
educator       M          69
               F          26
engineer       M          65
               F           2
entertainment  M          16
               F           2
executive      M          29
               F           3
healthcare     F          11
               M           5
homemaker      F           6
               M           1
lawyer         M          10
               F           2
librarian      F          29
               M          22
marketing      M          16
               F          10
none           M           5
               F           4
other          M          69
               F          36
programmer     M          60
               F           6
retired        M          13
               F           1
salesman       M           9
               F           3
scientist      M          28
               F           3
student        M         136
               F          60
technician     M          26
               F           1
writer         M          26
               F          19
Name: count, dtype: int64

       occupation gender       ratio
0   administrator      F   45.569620
1   administrator      M   54.430380
2          artist      F   46.428571
3          artist      M   53.571429
4          doctor      M  100.000000
5        educator      F   27.368421
6        educator      M   72.631579
7        engineer      F    2.985075
8        engineer      M   97.014925
9   entertainment      F   11.111111
10  entertainment      M   88.888889
11      executive      F    9.375000
12      executive      M   90.625000
13     healthcare      F   68.750000
14     healthcare      M   31.250000
15      homemaker      F   85.714286
16      homemaker      M   14.285714
17         lawyer      F   16.666667
18         lawyer      M   83.333333
19      librarian      F   56.862745
20      librarian      M   43.137255
21      marketing      F   38.461538
22      marketing      M   61.538462
23           none      F   44.444444
24           none      M   55.555556
25          other      F   34.285714
26          other      M   65.714286
27     programmer      F    9.090909
28     programmer      M   90.909091
29        retired      F    7.142857
30        retired      M   92.857143
31       salesman      F   25.000000
32       salesman      M   75.000000
33      scientist      F    9.677419
34      scientist      M   90.322581
35        student      F   30.612245
36        student      M   69.387755
37     technician      F    3.703704
38     technician      M   96.296296
39         writer      F   42.222222
40         writer      M   57.777778

occupation
administrator     43
artist            15
doctor             7
educator          69
engineer          65
entertainment     16
executive         29
healthcare         5
homemaker          1
lawyer            10
librarian         22
marketing         16
none               5
other             69
programmer        60
retired           13
salesman           9
scientist         28
student          136
technician        26
writer            26
Name: gender_n, dtype: int64

student          196
other            105
educator          95
administrator     79
engineer          67
programmer        66
librarian         51
writer            45
executive         32
scientist         31
artist            28
technician        27
marketing         26
entertainment     18
healthcare        16
retired           14
lawyer            12
salesman          12
none               9
homemaker          7
doctor             7
Name: occupation, dtype: int64

doctor           100.0%
engineer         97.01%
technician        96.3%
retired          92.86%
programmer       90.91%
executive        90.62%
scientist        90.32%
entertainment    88.89%
lawyer           83.33%
salesman          75.0%
educator         72.63%
student          69.39%
other            65.71%
marketing        61.54%
writer           57.78%
none             55.56%
administrator    54.43%
artist           53.57%
librarian        43.14%
healthcare       31.25%
homemaker        14.29%
dtype: object

### Step 6. For each occupation, calculate the minimum and maximum ages

In [ ]:
users.groupby("occupation")["age"].describe()[["min", "max"]]

                min   max
occupation
administrator  21.0  70.0
artist         19.0  48.0
doctor         28.0  64.0
educator       23.0  63.0
engineer       22.0  70.0
entertainment  15.0  50.0
executive      22.0  69.0
healthcare     22.0  62.0
homemaker      20.0  50.0
lawyer         21.0  53.0
librarian      23.0  69.0
marketing      24.0  55.0
none           11.0  55.0
other          13.0  64.0
programmer     20.0  63.0
retired        51.0  73.0
salesman       18.0  66.0
scientist      23.0  55.0
student         7.0  42.0
technician     21.0  55.0
writer         18.0  60.0

### Step 7. For each combination of occupation and gender, calculate the mean age

In [15]:
users.groupby(["occupation", "gender"])["age"].mean().to_frame()

                            age
occupation    gender
administrator F       40.638889
              M       37.162791
artist        F       30.307692
              M       32.333333
doctor        M       43.571429
educator      F       39.115385
              M       43.101449
engineer      F       29.500000
              M       36.600000
entertainment F       31.000000
              M       29.000000
executive     F       44.000000
              M       38.172414
healthcare    F       39.818182
              M       45.400000
homemaker     F       34.166667
              M       23.000000
lawyer        F       39.500000
              M       36.200000
librarian     F       40.000000
              M       40.000000
marketing     F       37.200000
              M       37.875000
none          F       36.500000
              M       18.600000
other         F       35.472222
              M       34.028986
programmer    F       32.166667
              M       33.216667
retired       F       70.000000
              M       62.538462
salesman      F       27.000000
              M       38.555556
scientist     F       28.333333
              M       36.321429
student       F       20.750000
              M       22.669118
technician    F       38.000000
              M       32.961538
writer        F       37.631579
              M       35.346154

### Step 8.  For each occupation present the percentage of women and men

In [37]:
total = users.groupby(["occupation", "gender"]).size().unstack(fill_value=0)
p_mujer = (total.loc[:, "F"] / total.sum(axis=1)) * 100
p_hombre = (total.loc[:, "M"] / total.sum(axis=1)) * 100

total["Porcentaje_F"] = p_mujer
total["Porcentaje_M"] = p_hombre

total

gender          F    M  Porcentaje_F  Porcentaje_M
occupation
administrator  36   43     45.569620     54.430380
artist         13   15     46.428571     53.571429
doctor          0    7      0.000000    100.000000
educator       26   69     27.368421     72.631579
engineer        2   65      2.985075     97.014925
entertainment   2   16     11.111111     88.888889
executive       3   29      9.375000     90.625000
healthcare     11    5     68.750000     31.250000
homemaker       6    1     85.714286     14.285714
lawyer          2   10     16.666667     83.333333
librarian      29   22     56.862745     43.137255
marketing      10   16     38.461538     61.538462
none            4    5     44.444444     55.555556
other          36   69     34.285714     65.714286
programmer      6   60      9.090909     90.909091
retired         1   13      7.142857     92.857143
salesman        3    9     25.000000     75.000000
scientist       3   28      9.677419     90.322581
student        60  136     30.612245     69.387755
technician      1   26      3.703704     96.296296
writer         19   26     42.222222     57.777778